"""
Build the in-game score (session 13) from the user's source files in assets/music/ (never modified):

  The_Last_Canopy_Sleeps.mp3  -> public/assets/music/canopy_NN.ogg   exploration, streamed in overlapping segments
  Savage_Ritual.mp3           -> public/assets/music/ritual.ogg      combat, decoded whole (it loops sample-accurately)
  + src/data/musicManifest.json (segment grid, durations, loudness) read by src/audio/Music.ts

Why Ogg Opus: exact sample positions (the pre-skip and the final granule trim the codec's padding, unlike an MP3's
encoder delay), a smaller download than the 192 kbps MP3s at 160 kbps (transparent for this material), and the same
Ogg container every other sound of the game already uses.

Why segments for the exploration score: decoded at 48 kHz stereo, its two minutes are ~46 MB of PCM. Split into
SEG-second pieces with OVERLAP seconds of shared audio at each join, only the piece playing and the next one are
decoded (~2 x 6 MB); Music.ts schedules them back to back on the audio clock and crossfades the shared overlap
(identical samples, a linear crossfade: no level change, no click).

usage: python tools/build_music.py        (needs ffmpeg with libopus)
"""
import json
import os
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, 'assets', 'music')
OUT = os.path.join(ROOT, 'public', 'assets', 'music')
MANIFEST = os.path.join(ROOT, 'src', 'data', 'musicManifest.json')
SR = 48000
BITRATE = '160k'
SEG = 12.0        # seconds of new music per exploration segment
OVERLAP = 0.08    # seconds shared with the next segment (crossfaded at runtime)


def run(args):
    r = subprocess.run(args, capture_output=True, text=True)
    if r.returncode != 0:
        sys.exit('ffmpeg failed: ' + ' '.join(args) + '\n' + r.stderr[-2000:])
    return r


def duration(path):
    r = run(['ffprobe', '-v', 'error', '-show_entries', 'format=duration', '-of', 'default=nw=1:nk=1', path])
    return float(r.stdout.strip())


def loudness(path):
    r = subprocess.run(['ffmpeg', '-hide_banner', '-i', path, '-af', 'ebur128=framelog=quiet', '-f', 'null', '-'], capture_output=True, text=True)
    lufs = None
    for line in r.stderr.splitlines():
        s = line.strip()
        if s.startswith('I:') and 'LUFS' in s:
            lufs = float(s.split()[1])
    return lufs


def opus(src, dst, start=None, end=None):
    af = f'aresample={SR}'
    if start is not None:
        # sample-exact cut on the resampled stream
        af += f',atrim=start_sample={start}:end_sample={end},asetpts=PTS-STARTPTS'
    run(['ffmpeg', '-v', 'error', '-y', '-i', src, '-af', af, '-c:a', 'libopus', '-b:a', BITRATE, '-vbr', 'on',
         '-application', 'audio', '-frame_duration', '20', dst])


def main():
    os.makedirs(OUT, exist_ok=True)
    canopy = os.path.join(SRC, 'The_Last_Canopy_Sleeps.mp3')
    ritual = os.path.join(SRC, 'Savage_Ritual.mp3')
    for f in (canopy, ritual):
        if not os.path.exists(f):
            sys.exit('missing ' + f)
    for old in os.listdir(OUT):
        if old.startswith('canopy_') or old == 'ritual.ogg':
            os.remove(os.path.join(OUT, old))

    # ---- exploration: overlapping segments on a 48 kHz sample grid
    dur = duration(canopy)
    total = int(round(dur * SR))
    step, ov = int(SEG * SR), int(OVERLAP * SR)
    segs = []
    i = 0
    while i * step < total - SR // 2:   # (no sliver of a segment after the last full one)
        a = i * step
        b = min(total, (i + 1) * step + ov)
        name = f'canopy_{i:02d}.ogg'
        opus(canopy, os.path.join(OUT, name), a, b)
        segs.append({'url': 'assets/music/' + name, 'start': a / SR, 'length': (b - a) / SR, 'bytes': os.path.getsize(os.path.join(OUT, name))})
        i += 1

    # ---- combat: one file
    opus(ritual, os.path.join(OUT, 'ritual.ogg'))

    man = {
        'note': 'generated by tools/build_music.py from assets/music/ (session 13)',
        'explore': {
            'source': 'The_Last_Canopy_Sleeps.mp3', 'duration': dur, 'lufs': loudness(canopy),
            'segment': SEG, 'overlap': OVERLAP, 'segments': segs,
        },
        'combat': {
            'source': 'Savage_Ritual.mp3', 'duration': duration(ritual), 'lufs': loudness(ritual),
            'url': 'assets/music/ritual.ogg', 'bytes': os.path.getsize(os.path.join(OUT, 'ritual.ogg')),
        },
    }
    with open(MANIFEST, 'w', encoding='utf8') as f:
        json.dump(man, f, indent=1)
    kb = sum(s['bytes'] for s in segs) / 1024
    print(f"explore: {len(segs)} segments, {kb:.0f} KB, {dur:.2f} s, {man['explore']['lufs']} LUFS")
    print(f"combat: {man['combat']['bytes'] / 1024:.0f} KB, {man['combat']['duration']:.2f} s, {man['combat']['lufs']} LUFS")


if __name__ == '__main__':
    main()
