/**
 * Hero animation manifest — gameplay-facing view of the 49 supplied Mixamo clips.
 *
 * Source of truth for clip facts: src/data/heroAnimations.json, generated by tools/blender/build_hero.py
 * from 'assets/characters/hero/Sword and Shield Pack.zip' (durations, root-motion curves, and
 * sword/foot/shield speed peaks measured from the actual motion). Classification was authored from the
 * rendered contact sheets (tools/blender/hero_clip_map.json).
 *
 * Session 5 added 24 clips from 'Great Sword Pack.zip' (two-handed techniques, the sword guard set, hits, deaths) and
 * the loose 'Crouch Walking.fbx' (a real crouch-walk loop, 1.21 m/s): tools/blender/hero_clip_map.json extraClips
 * (+ the unused Great Sword clips with reasons). Dodge is still a directional dash (no roll clip in any pack).
 */
import raw from './heroAnimations.json';

export type ClipCategory =
  | 'idle' | 'locomotion' | 'combat_locomotion' | 'crouch' | 'jump' | 'block' | 'light_attack'
  | 'heavy_attack' | 'combo' | 'kick_bash' | 'shield' | 'reaction' | 'death' | 'misc';

export interface Peak { t: number; speed: number; window: [number, number]; }
export interface ClipInfo {
  source: string; cat: ClipCategory; loop: boolean; root: 'loop' | 'extract' | 'extract_jump';
  frames: number; duration: number; note?: string;
  rootVelocity?: [number, number]; speed?: number;
  rootCurve?: [number, number][]; rootTotal?: [number, number]; hipsRise?: number[];
  hipsHeight: [number, number];
  swordPeaks: Peak[]; footPeaks: Peak[]; shieldPeaks: Peak[];
}

export const HERO_CLIPS = (raw as unknown as { clips: Record<string, ClipInfo> }).clips;
export const HERO_FPS = (raw as unknown as { fps: number }).fps;

/** Categorised inventory (every clip appears exactly once). */
export const INVENTORY: Record<string, string[]> = {
  idle: ['idle_combat', 'idle_alert', 'idle_flourish_a', 'idle_flourish_b'],
  locomotion: ['walk_fwd', 'run_fwd', 'turn_left_90', 'turn_right_90', 'turn_180', 'turn_180_fast'],
  combat_locomotion: ['walk_back', 'run_back', 'strafe_walk_left', 'strafe_walk_right', 'strafe_run_left', 'strafe_run_right'],
  crouch: ['crouch_enter', 'crouch_exit', 'crouch_idle', 'crouch_ready', 'crouch_walk'],
  jump_fall_land: ['jump_stand', 'jump_run'],
  rolls_dodges: [], // none in any pack — dash dodge uses run_fwd / run_back / strafe_run_* at high playback rate
  blocks_parries: ['block_enter', 'block_idle', 'block_exit', 'block_impact', 'crouch_block_enter', 'crouch_block_idle', 'crouch_block_impact', 'crouch_block_exit',
    'gs_block_enter', 'gs_block_idle', 'gs_block_exit', 'gs_block_impact', 'gs_crouch_block_enter', 'gs_crouch_block_idle', 'gs_crouch_block_exit', 'gs_crouch_block_impact'],
  light_attacks: ['atk_chop', 'atk_rising_cut', 'atk_lunge_cut', 'atk_crouch_sweep', 'gs_cleave', 'gs_quick_cut', 'gs_low_sweep', 'gs_crouch_sweep'],
  heavy_attacks: ['atk_spin_slash', 'atk_leap_slam', 'atk_jump_spin', 'gs_high_spin', 'gs_leap_spin', 'gs_slide_cut', 'gs_plunge'],
  combo_candidates: ['atk_advancing_sweep', 'atk_whirlwind', 'gs_spin_double', 'gs_rampage'],
  shield_actions: ['shield_bash'],
  kick_bash: ['kick_front', 'gs_spin_kick'],
  reactions: ['hit_light', 'hit_heavy', 'gs_hit_light', 'gs_hit_heavy'],
  knockdown: [], // no dedicated knockdown/get-up clip for the hero; heavy reactions use hit_heavy
  death: ['death_back', 'death_kneel', 'gs_death_forward', 'gs_death_collapse'],
  misc: ['shift_channel', 'power_up', 'sheath', 'unsheath'],
};

/** Clips the controller loops. */
export const LOOPING = new Set(Object.entries(HERO_CLIPS).filter(([, c]) => c.loop).map(([k]) => k));

/** Jump phases (frames @30fps) measured from hipsRise in the manifest. */
export const JUMP_PHASES = {
  jump_stand: { takeoff: [0, 5], rise: [5, 13], apex: 14, fall: [15, 23], land: [23, 29] },
  jump_run: { takeoff: [0, 2], rise: [2, 11], apex: 12, fall: [13, 22], land: [22, 25] },
} as const;

export function clip(id: string): ClipInfo {
  const c = HERO_CLIPS[id];
  if (!c) throw new Error(`Clip "${id}" not in heroAnimations.json`);
  return c;
}

/** Sample the extracted root-motion curve (character space [forward, right]) at clip time t. */
export function rootAt(id: string, t: number): [number, number] {
  const c = HERO_CLIPS[id];
  if (!c?.rootCurve) return [0, 0];
  const f = Math.max(0, Math.min(c.rootCurve.length - 1, t * HERO_FPS));
  const i = Math.floor(f);
  const j = Math.min(c.rootCurve.length - 1, i + 1);
  const k = f - i;
  const a = c.rootCurve[i], b = c.rootCurve[j];
  return [a[0] + (b[0] - a[0]) * k, a[1] + (b[1] - a[1]) * k];
}

// sanity: inventory covers every clip exactly once
{
  const seen = new Set<string>();
  for (const list of Object.values(INVENTORY)) for (const id of list) {
    if (seen.has(id)) throw new Error('Clip listed twice in INVENTORY: ' + id);
    if (!HERO_CLIPS[id]) throw new Error('INVENTORY lists unknown clip: ' + id);
    seen.add(id);
  }
  const missing = Object.keys(HERO_CLIPS).filter((k) => !seen.has(k));
  if (missing.length) throw new Error('Clips missing from INVENTORY: ' + missing.join(', '));
}
